const styles = {
  container: {
    flex: "1 0 calc(32.75% + 1px)",
    scrollSnapAlign: "center",
    scrollSnapStop: "always",
    display: "flex",
    flexDirection: "column",
  },
  top: {
    maxWidth: "none",
    appearance: "none",
    background: "transparent",
    border: 0,
    cursor: "pointer",
    margin: 0,
    padding: 0,
    width: "100%",
    filter: "drop-shadow(0px 8px 6px rgba(0, 0, 0, 0.25))",
    overflow: "hidden",
  },
  bottom: {
    opacity: 1,
    pointerEvents: "auto",
    paddingRight: 24,
    willChange: "opacity",
    transition: "visibility .33s ease-in-out",
  },
  hostphoto: {
    borderRadius: 4,
    paddingTop: "100%",
    position: "relative",
    flex: 1,
    backgroundPosition: "50% 50%",
    backgroundRepeat: "no-repeat",
  },
  hostphotogrid: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  image: {
    objectFit: "cover",
    objectPosition: "center bottom",
    borderRadius: 4,
    height: "100%",
    width: "100%",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    position: "absolute",
  },
  background: {
    backgroundImage: "none",
    backgroundSize: "cover",
    borderRadius: 4,
    display: "none",
    backgroundPosition: "50% 50%",
    backgroundRepeat: "no-repeat",
    inset: 0,
    position: "absolute",
    height: "100%",
    width: "100%",
    verticalAlign: "bottom",
  },
  text: {
    color: "black",
    fontSize: 26,
    lineHeight: "30px",
    marginTop: 48,
    marginBottom: 34,
    paddingRight: 24,
  },
  signature: {
    display: "inline-block",
    verticalAlign: "bottom",
    height: 32,
    width: "auto",
    minHeight: 1,
    backgroundPosition: "50% 50%",
    backgroundRepeat: "no-repeat",
  },
  sign_img: {
    objectFit: "contain",
    objectPosition: "left center",
    verticalAlign: "bottom",
    height: "100%",
    width: "100%",
    position: "static",
  },
  location: {
    marginTop: 24,
    color: "#717171",
    fontSize: 16,
    lineHeight: "20px",
  },
};

export default styles